import React, {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MessageCircle,Users,Kanban,HardDrive,Activity,Settings,Plus,Send,Square,ChevronRight} from 'lucide-react';
import './style.css';

type Agent={id:string,name:string,role:string,model:string,tools:string,workspace_id:string|null};
type Channel={id:string,kind:string,title:string};
type Message={id:string,channel_id:string,author_id:string,body:string,created_at:string};
type Workspace={id:string,name:string,path:string};
type Task={id:string,title:string,description:string,status:string,assignee_id:string|null,workspace_id:string|null,pr_url?:string|null};
type Run={id:string,agent_id:string,channel_id:string,status:string,error?:string,cost:number};
type State={agents:Agent[],channels:Channel[],workspaces:Workspace[],tasks:Task[],runs:Run[]};
const empty:State={agents:[],channels:[],workspaces:[],tasks:[],runs:[]};
async function api(path:string,init?:RequestInit){const r=await fetch('/api'+path,{...init,headers:{'Content-Type':'application/json',...(init?.headers||{})}});if(!r.ok){let e;try{e=await r.json()}catch{};throw new Error(e?.error||`HTTP ${r.status}`)}return r.json()}
function App(){
 const [state,setState]=useState<State>(empty),[page,setPage]=useState('Chat'),[selected,setSelected]=useState(''),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(''),[models,setModels]=useState<{provider:string,id:string,name:string}[]>([]),[error,setError]=useState(''),[modal,setModal]=useState(''),[busy,setBusy]=useState(false);
 const refresh=()=>api('/state').then(setState).catch(e=>setError(e.message));
 useEffect(()=>{refresh();api('/models').then(setModels).catch(()=>{});const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/events`);ws.onmessage=e=>{const event=JSON.parse(e.data);if(event.type==='message'&&event.message.channel_id===selected)setMessages(old=>old.some(m=>m.id===event.message.id)?old:[...old,event.message]);if(event.type==='run'||event.type==='task')refresh()};return()=>ws.close()},[selected]);
 useEffect(()=>{if(selected)api(`/channels/${selected}/messages`).then(setMessages).catch(e=>setError(e.message))},[selected]);
 const channel=state.channels.find(c=>c.id===selected),running=state.runs.filter(r=>r.channel_id===selected&&r.status==='running');
 const submit=async()=>{if(!draft.trim()||!selected)return;const text=draft;setDraft('');try{await api(`/channels/${selected}/messages`,{method:'POST',body:JSON.stringify({text})});refresh()}catch(e:any){setError(e.message);setDraft(text)}};
 const nav=[['Chat',MessageCircle],['Agents',Users],['Tasks',Kanban],['Workstations',HardDrive],['Activity',Activity],['Settings',Settings]] as const;
 return <div className="app"><header><div className="brand"><div className="brand-icon">✳</div><span>hive<span className="brand-dot">.</span></span></div><nav>{nav.map(([label,Icon])=><button className={page===label?'active':''} onClick={()=>setPage(label)} key={label}><Icon size={17}/><span>{label}</span></button>)}</nav><div className="server"><i/> Local workspace</div></header>
 {error&&<div className="error" onClick={()=>setError('')}>{error} <span>×</span></div>}
 {page==='Chat'&&<main className="chat"><aside className="sidebar"><div className="section-title"><span>Conversations</span><button className="icon-button" title="New group" onClick={()=>setModal('group')}><Plus size={18}/></button></div><div className="side-list">{state.channels.map(c=><button className={`conversation ${selected===c.id?'chosen':''}`} key={c.id} onClick={()=>setSelected(c.id)}><div className="avatar">{c.kind==='group'?'#':c.title.slice(0,1).toUpperCase()}</div><div><strong>{c.title}</strong><small>{c.kind==='group'?'Group conversation':'Direct message'}</small></div><ChevronRight size={15}/></button>)}{!state.channels.length&&<div className="empty-side">Create an agent to begin a conversation.</div>}</div><div className="side-foot"><span>{state.agents.length} agents</span><span>{state.channels.length} channels</span></div></aside><section className="conversation-pane">{channel?<><div className="conversation-head"><div className="avatar large">{channel.kind==='group'?'#':channel.title.slice(0,1).toUpperCase()}</div><div><h2>{channel.title}</h2><p>{channel.kind==='group'?'Group conversation':'Private conversation'}</p></div>{running.length>0&&<span className="working">Agent working…</span>}{running.length>0&&<button className="ghost" onClick={()=>{const r=running[0];api(`/agents/${r.agent_id}/stop`,{method:'POST',body:JSON.stringify({channel_id:selected})}).then(refresh)}}><Square size={14}/> Stop</button>}</div><div className="messages">{messages.map(m=><div className={`message ${m.author_id==='human'?'mine':''}`} key={m.id}><div className="message-avatar">{m.author_id==='human'?'Y':state.agents.find(a=>a.id===m.author_id)?.name.slice(0,1)||'A'}</div><div><div className="message-meta"><strong>{m.author_id==='human'?'You':state.agents.find(a=>a.id===m.author_id)?.name||'Agent'}</strong><span>{new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span></div><div className="message-body">{m.body}</div></div></div>)}{running.length>0&&<div className="typing"><span/><span/><span/> Working on it</div>}{!messages.length&&<div className="empty-main"><div className="empty-glyph">✳</div><h2>Start a conversation</h2><p>Messages sent here wake the assigned agent.</p></div>}</div>{channel.kind==='agent_dm'?<div className="hint">Agent private chat · read only</div>:<><div className="composer"><textarea placeholder={`Message ${channel.title}…`} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit()}}}/><button onClick={submit} disabled={!draft.trim()}><Send size={17}/></button></div><div className="hint">Enter to send · Shift+Enter for new line</div></>}</>:<div className="empty-main"><div className="empty-glyph">✳</div><h2>Your team starts here</h2><p>Select a conversation, or create your first agent.</p><button className="primary" onClick={()=>{setPage('Agents');setModal('agent')}}>Create agent</button></div>}</section></main>}
 {page==='Agents'&&<main className="content"><div className="page-heading"><div><div className="eyebrow">YOUR TEAM</div><h1>Agents</h1><p>Give each agent a role, model, workspace, and explicit tool access.</p></div><button className="primary" onClick={()=>setModal('agent')}><Plus size={17}/> New agent</button></div><div className="cards">{state.agents.map(a=><AgentCard key={a.id} agent={a} workspaces={state.workspaces} onSave={refresh} onError={setError}/>)}{!state.agents.length&&<div className="empty-card">No agents yet. Create one to start a private chat.</div>}</div></main>}
 {page==='Tasks'&&<main className="content"><div className="page-heading"><div><div className="eyebrow">WORK IN MOTION</div><h1>Tasks</h1><p>Track work from idea to review and completion.</p></div><button className="primary" onClick={()=>setModal('task')}><Plus size={17}/> New task</button></div><div className="board">{['todo','in_progress','in_review','blocked','done'].map(status=><div className="column" key={status}><div className="column-head"><span>{status.replace('_',' ')}</span><b>{state.tasks.filter(t=>t.status===status).length}</b></div>{state.tasks.filter(t=>t.status===status).map(t=><div className="task-card" key={t.id}><strong>{t.title}</strong>{t.pr_url&&<a className="pr-link" href={t.pr_url} target="_blank" rel="noreferrer">View PR ↗</a>}<p>{t.description}</p><div className="task-bottom"><span>{state.agents.find(a=>a.id===t.assignee_id)?.name||'Unassigned'}</span><select value={t.status} onChange={e=>api(`/tasks/${t.id}`,{method:'PATCH',body:JSON.stringify({status:e.target.value})}).then(refresh).catch(x=>setError(x.message))}>{['todo','in_progress','in_review','blocked','done'].map(s=><option key={s}>{s}</option>)}</select></div></div>)}</div>)}</div></main>}
 {page==='Workstations'&&<main className="content"><div className="page-heading"><div><div className="eyebrow">LOCAL RESOURCES</div><h1>Workstations</h1><p>Workspaces on /Volumes/Data. Agents receive only the tools you grant.</p></div><button className="primary" onClick={()=>setModal('workspace')}><Plus size={17}/> Add workspace</button></div><div className="cards">{state.workspaces.map(w=><div className="card" key={w.id}><div className="card-icon"><HardDrive size={22}/></div><h3>{w.name}</h3><p className="mono">{w.path}</p><div className="card-rule"/><div className="card-muted">{state.agents.filter(a=>a.workspace_id===w.id).length} assigned agents</div></div>)}{!state.workspaces.length&&<div className="empty-card">Add an existing directory on /Volumes/Data.</div>}</div></main>}
 {page==='Activity'&&<main className="content"><div className="page-heading"><div><div className="eyebrow">OPERATIONS</div><h1>Activity</h1><p>Recent agent runs and their outcomes.</p></div></div><div className="activity-list">{state.runs.map(r=><div className="activity-row" key={r.id}><div className={`status-dot ${r.status}`}/><div><strong>{state.agents.find(a=>a.id===r.agent_id)?.name||'Agent'}</strong><small>{r.id.slice(0,8)}</small></div><span className="run-status">{r.status}</span><span className="run-cost">${Number(r.cost||0).toFixed(4)}</span>{r.error&&<div className="run-error">{r.error}</div>}</div>)}{!state.runs.length&&<div className="empty-card">No runs yet.</div>}</div></main>}
 {page==='Settings'&&<main className="content"><div className="page-heading"><div><div className="eyebrow">PREFERENCES</div><h1>Settings</h1><p>Local service configuration and model availability.</p></div></div><div className="settings-grid"><div className="card"><h3>Connection</h3><p>Hive listens on this Mac. Your access link is generated on startup.</p><div className="setting-line"><span>Available OpenRouter models</span><b>{models.length}</b></div><div className="setting-line"><span>Data storage</span><b>External drive</b></div></div><div className="card"><h3>Security boundary</h3><p>Workspace file tools check paths and symlinks. Arbitrary shell access is disabled because it cannot be safely isolated under the current user without a system sandbox.</p></div></div></main>}
 {modal&&<Modal kind={modal} close={()=>setModal('')} state={state} models={models} done={()=>{setModal('');refresh()}} error={setError}/>}
 </div>
}
function AgentCard({agent:a,workspaces,onSave,onError}:{agent:Agent,workspaces:Workspace[],onSave:()=>void,onError:(s:string)=>void}){const [tools,setTools]=useState<string[]>(JSON.parse(a.tools));const [workspace,setWorkspace]=useState(a.workspace_id||'');const [role,setRole]=useState(a.role);const save=()=>api(`/agents/${a.id}`,{method:'PATCH',body:JSON.stringify({tools,workspace_id:workspace||null,role})}).then(onSave).catch(e=>onError(e.message));const toggle=(t:string)=>setTools(tools.includes(t)?tools.filter(x=>x!==t):[...tools,t]);return <div className="card agent-card"><div className="agent-top"><div className="avatar large">{a.name.slice(0,1).toUpperCase()}</div><div><h3>{a.name}</h3><small>{a.model}</small></div><span className="online-dot"/></div><textarea className="role-edit" value={role} onChange={e=>setRole(e.target.value)} placeholder="Agent role and instructions"/><label className="field-label">Workspace<select value={workspace} onChange={e=>setWorkspace(e.target.value)}><option value="">No workspace</option>{workspaces.map(w=><option value={w.id} key={w.id}>{w.name}</option>)}</select></label><div className="field-label">Tools</div><div className="chips">{['send_message','agent_directory','message_agent','task_list','task_create','task_assign','task_handoff','task_update','ws_list','ws_read','ws_write','ws_bash','git_status','git_push','pr_create'].map(t=><button key={t} className={tools.includes(t)?'enabled':''} onClick={()=>toggle(t)}>{t}</button>)}</div><button className="save" onClick={save}>Save changes</button></div>}
function Modal({kind,close,state,models,done,error}:{kind:string,close:()=>void,state:State,models:{provider:string,id:string,name:string}[],done:()=>void,error:(s:string)=>void}){const [name,setName]=useState(''),[description,setDescription]=useState(''),[model,setModel]=useState(models.find(m=>m.provider==='openrouter')?.provider+'/'+models.find(m=>m.provider==='openrouter')?.id||''),[members,setMembers]=useState<string[]>([]),[assignee,setAssignee]=useState(''),[path,setPath]=useState('');const submit=async()=>{try{if(kind==='agent')await api('/agents',{method:'POST',body:JSON.stringify({name,role:description,model})});if(kind==='group')await api('/channels',{method:'POST',body:JSON.stringify({title:name,members})});if(kind==='task')await api('/tasks',{method:'POST',body:JSON.stringify({title:name,description,assignee_id:assignee||null})});if(kind==='workspace')await api('/workspaces',{method:'POST',body:JSON.stringify({name,path})});done()}catch(e:any){error(e.message)}};return <div className="scrim" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal"><div className="modal-top"><h2>{kind==='agent'?'New agent':kind==='group'?'New group':kind==='task'?'New task':'Add workspace'}</h2><button className="icon-button" onClick={close}>×</button></div><label>Name<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder={kind==='workspace'?'Project name':kind==='task'?'What needs doing?':'Give it a name'}/></label>{(kind==='agent'||kind==='task')&&<label>{kind==='agent'?'Role and instructions':'Description'}<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4}/></label>}{kind==='agent'&&<label>Model<select value={model} onChange={e=>setModel(e.target.value)}>{models.map(m=><option key={`${m.provider}/${m.id}`} value={`${m.provider}/${m.id}`}>{m.name||m.id}</option>)}</select></label>}{kind==='group'&&<div className="modal-members">Members{state.agents.map(a=><label key={a.id}><input type="checkbox" checked={members.includes(a.id)} onChange={e=>setMembers(e.target.checked?[...members,a.id]:members.filter(x=>x!==a.id))}/>{a.name}</label>)}</div>}{kind==='task'&&<label>Assign to<select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Unassigned</option>{state.agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}{kind==='workspace'&&<label>Absolute path on /Volumes/Data<input value={path} onChange={e=>setPath(e.target.value)} placeholder="/Volumes/Data/Code/my-project"/></label>}<div className="modal-actions"><button className="ghost" onClick={close}>Cancel</button><button className="primary" onClick={submit} disabled={!name.trim()}>{kind==='workspace'?'Add workspace':'Create'}</button></div></div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
